apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${{ values.serviceName }}
  namespace: ${{ values.serviceName }}
  labels:
    backstage.io/kubernetes-id: ${{ values.serviceName }}
spec:
  interval: 5m
  releaseName: ${{ values.serviceName }}
  chart:
    spec:
      chart: ./charts/app
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    name: ${{ values.serviceName }}
    replicaCount: ${{ values.replicas }}
    image:
      repository: ${{ values.imageRepository }}
      tag: "${{ values.imageTag }}"
    env:
      APP_ENV: "${{ values.appEnv }}"
      APP_MESSAGE: "${{ values.message }}"
