apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  labels:
    app.kubernetes.io/name: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backstage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backstage
      annotations:
        checksum/github-secret: {{ .Values.github.token | sha256sum }}
    spec:
      serviceAccountName: backstage
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: backstage
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 7007
              name: http
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.db.host | default (printf "backstage-db-rw.%s.svc.cluster.local" .Release.Namespace) }}
            - name: POSTGRES_PORT
              value: {{ .Values.db.port | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: password
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-github
                  key: token
            - name: APP_BASE_URL
              value: {{ .Values.baseUrl }}
            - name: BACKEND_BASE_URL
              value: {{ .Values.baseUrl }}
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
