apiVersion: v1
kind: Secret
metadata:
  name: backstage-github
  labels:
    app.kubernetes.io/name: backstage
type: Opaque
stringData:
  token: {{ required "github.token is required" .Values.github.token | quote }}
  {{- if .Values.githubAuth.enabled }}
  authClientId: {{ required "githubAuth.clientId is required when githubAuth.enabled" .Values.githubAuth.clientId | quote }}
  authClientSecret: {{ required "githubAuth.clientSecret is required when githubAuth.enabled" .Values.githubAuth.clientSecret | quote }}
  {{- end }}
  k8sDevToken: {{ .Values.clusters.dev.token | quote }}
  k8sProdToken: {{ .Values.clusters.prod.token | quote }}
