apiVersion: v1
kind: Secret
metadata:
  name: backstage-github
  labels:
    app.kubernetes.io/name: backstage
type: Opaque
stringData:
  token: {{ required "github.token is required" .Values.github.token }}
