apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${{ values.serviceName }}-secrets
  namespace: ${{ values.serviceName }}-${{ values.environment }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: ${{ values.serviceName }}-fake
  target:
    name: ${{ values.serviceName }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: app-secret
      remoteRef:
        key: ${{ values.serviceName }}/${{ values.environment }}/app-secret
