apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.serviceName }}-uat
resources:
  - namespace.yaml
  - ../../base/${{ values.serviceName }}
patches:
  - path: release-patch.yaml
