apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth
  description: Authentication and authorization microservice
  annotations:
    backstage.io/kubernetes-id: auth
    backstage.io/kubernetes-namespace: auth
    github.com/project-slug: duynhlab/auth-service
  tags: [go, microservice]
  links:
    - url: https://github.com/duynhlab/auth-service
      title: GitHub Repository
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: duynhlab-ecommerce
